### ISSUE TITLE
您好，我看了您的代码对我帮助很大，之后请把注释写清楚。我会一直follow

### ISSUE THREAD

**Issue by zhangsanIOS** [LOUSANPANG/fe-uniapp#1]
您好，我看了您的代码对我帮助很大，之后请把注释写清楚。我会一直follow

**Comment by LOUSANPANG** [comment]
thx~ 

刚刚重构了该仓库，使用 `cli` 重新构建封装了下代码。

这样在大项目应用中编译速度、热更新会更快。

同时对环境配置、公共组件、工具函数进行了优化。
